### ISSUE TITLE
Integrations review

### ISSUE THREAD

**Issue by tmpfs** [uwe-app/integrations#1]
Hi @chrism, when you have a moment can you please review the integrations.

You will need `0.40.9` for the `dynamic` flag support, just run:

```
uvm latest
uwe --version
```

To upgrade and verify your new version is sane. After that all the instructions in the readme should work as expected.

Remember you need to `yarn install` for each integration.

I have tested using node@14 - i should maybe add that version info to the readme?

Thanks as always for your help 👍

**Comment by tmpfs** [comment]
Heads up @chrism, the integration docs have been moved to the website so you should build the website to read them now.

Also I have switched the primary branch for the runtime from `master` to `main` so rather than upgrade (`uvm latest`) a clean install is probably better now:

```
uvm uninstall
curl https://release.uwe.app/install.sh | sh
```

Thanks :+1:

**Comment by chrism** [comment]
Sounds good will take a proper look this weekend @tmpfs 👍

**Comment by tmpfs** [comment]
Thanks a lot @chrism, I have also improved the content for the default blueprint with you can view with:

```
uwe new project-name
cd project-name && uwe --live
```

I have added another example integration for `postcss`; I also played a little with `snowpack` but their system is not pure Javascript (it is tied to HTML generation too it seems) and their docs are not particularly good. 

Under the hood `snowpack` uses `esbuild` so I can't see that it offers too much value when people could just use `esbuild` directly.

**Comment by chrism** [comment]
hi @tmpfs

I got an error when I tried to follow this–check it out.

The install worked OK but I couldn't run `uwe --live`.

```
 INFO  release::install  > Installed uwe@0.40.13 ✓
~/git » uwe --version
uwe 0.40.13
~/git » uwe new uwe-test-project
~/git » cd uwe-test-project                         
git/uwe-test-project [main] » uwe --live              
 INFO  workspace::options > mkdir /Users/chrismasters/git/uwe-test-project/build/debug
 ERROR uwe::opts          > Plugin directory /Users/chrismasters/.uwe/cache/src/std::core::4.1.6 does not exist, remove the lock file and try again
```

**Comment by tmpfs** [comment]
Sorry about that @chrism , it is bug my end. i hacked together the plugin system really quickly and it needs a decent refactor to fix this and a few other bugs.

The workaround for now is to remove `site.lock` and try again.

**Comment by chrism** [comment]
Hi again @tmpfs – after removing the `site.lock` and rerunning it worked, thanks!

Something I noticed, which I think could just be timing... is that shortly after I did that it broke again when trying to restart after updating the `header.hbs`.

```
ERROR uwe::opts          > Plugin directory /Users/chrismasters/.uwe/cache/src/std::core::4.1.9 does not exist, remove the lock file and try again```

I guessed you might have been updating so deleted the `site.lock` again and then it worked–updating to 4.1.10.

fwiw this is confusing, but I imagine you know this and its just while you are rapidly developing? In reality the older versions would still be available? (sorry if i misunderstand the process but guess its a little like package versions).

I've managed to add a page and the link in the header.

The restarting of the server after some changes is taking a bit of getting used to–but that is something you are working on I get the impression from `... currently requires a restart ...`.

Also I've had this error

```
ERROR uwe::opts              > panicked at 'called `Option::unwrap()` on a `None` value', /home/muji/git/uwe/app/components/compiler/src/run.rs:40:40
```

But I'm not exactly sure why (only once). And had to restart.

Final point, to remove the default styling I was a little bit confused by the text–maybe something like,

> remove these two lines from `site.toml` where it includes the styling
> [dependencies."std::core".apply]
> styles = ["**"]

rather than what is left. I dunno just a thought.

But that all said this thing is really, really nice! It rebuilds so quickly and feels very ergonomic.

Am really excited by building stuff with it!!

Don't think I will get chance to follow the tailwind stuff today but will very soon, looking forward to checking it out!

Please keep me posted for when you think it might be possible to incorporate a blog–I now realise that what we spoke about, where the blog could be namespaced to a folder is essential too.

I think I might start writing the `.md` files anyway and transfer it over to a new project with a blog once it is ready... that way I can start testing stuff out sooner.

Really, really great stuff! 👍

**Comment by tmpfs** [comment]
A lot of really useful feedback here, thanks @chrism!

Apologies for the plugin bugs, please bear with me, I know it is inconvenient and will fix them! Glad you managed to get it working. From my point of view the plugin installation must be excellent so I want to invest a decent chunk of time into the plugin rewrite once other aspects are stable.

Your point about the language for removing the styles in the default blueprint is a good one and I have updated it; next time you get a chance take a look and let me know if you think it is still not clear.

The error with `Option::unwrap()` is to do with adding and removing files during live reload; I am working on this right now but it is quite complicated, there are some issues open in the app repo for this.

You point about needing to set up a blog for a folder is important to hear right now as I have been thinking hard about how best to handle this scenario for *archetypes* (maybe `format` is a better word?). It would be good to discuss this elsewhere to see if we can work out an ergonomic solution. Currently, I am leaning to settings files within folders that would transform the content; stuff like `blog.toml`, `book.toml` and `slideshow.toml`. I think these would be very opinionated in terms of file system layout.

**Comment by chrism** [comment]
> Apologies for the plugin bugs, please bear with me, I know it is inconvenient and will fix them!

Sure no problem @tmpfs I totally appreciate thats part of the process, happy to try to squash them!

I was thinking about your last point about the different behaviours and how to manage them.

Personally, I think _archetypes_ maybe sounds a little much/technical. _Format_ is better for me, but maybe there is another word...I dunno I was thinking about maybe _primitive_ like the Platonic primitives... might be something there?

Anyway wording aside was my main thought on how I'd like the DX to be.

I don't think that the settings files within folders would be so convenient for me–what I'd prefer is to have is a kind of router type view where I could see what the site architecture is.

I feel like this would be simple for sites because there would probably only ever be a couple of different primitives used.

So for my case I think it would be something like this...

- Articles => blog
- Work => portfolio (if this primitive exists)

And the rest would just be standard pages.

So I think that this could be included in the `site.toml` nicely? Something where you just specify the name of the folder, the primitive and what you would like the naming to map to?

```
[primitive]
name = "Articles"
type = "blog"
entrypoint = "/articles"

[primitive]
name = "Work"
type = "portfolio"
entrypoint = "/work"
```

I feel like this way you could also have a nice way of maybe seeing this with a command then?

Something like

```
uwe primitives list
```

Would list them, and you could even add/remove with something like

```
uwe primitive add blog Articles
```

No idea whether this is feasible/a good idea but thought I'd share it as I think this would be pretty ideal!

**Comment by tmpfs** [comment]
@chrism, this is really useful, thanks :+1:  I can see this working, internally I would just expand out the *primitive* to more complex settings, so they would just be a nice way to abstract away a lot of settings and some conventions.

I need to think it through some more but I think this could work well, excellent idea, thank you!

**Comment by chrism** [comment]
Glad to hear it and happy to help! 👍

**Comment by tmpfs** [comment]
Hi @chrism, I have just released `0.40.17` which should fix the `Option::unwrap()` bug completely; upgrade with `uvm latest`.

This is exciting as it represents a milestone for the live reload functionality; creating and deleting files should now keep the internal data structures in sync. The caveat is that currently templates (with `.hbs` extension) in layouts, partials and other locations are still not handled; I have just raised an issue for this.

But it does mean that the basic live reload for Markdown/HTML should work as expected now including changing properties in the page front matter. Here is how I tested it:

* Open the `site/index.md` file and make a change to verify it reloads
* Create a `site/foo.md` file and enter some text
* Edit the `site/index.md` to create a link to the new page (`[[foo]]`) and save it (the link should be created in the web page)
* Delete the `site/foo.md` file
* Save the `site/index.md` file again and an error should show in the browser as the link is no longer valid

To test editing front matter I normally just update the page front matter:

```toml
+++
title = "Foo test"
+++
```

I am sure there are lots more bugs but this is a good step in the right direction for a good editing experience.

FYI, I have also pushed an update to the website repository that removes the `path` from the `std::core` dependency and updates the version (deleting `site.lock` may be necessary and you may need to update the local copy of the runtime assets manually `uvm runtime`).

**Comment by chrism** [comment]
Thanks, with the latest version `0.40.17` and pulling down the latest version of the website I got it working.

I had to delete the `site.lock` again though before it ran. Which got me wondering about why it is included in the repo. Usually I'm more used to it being ignored with Ruby `gemfile.lock` or `yarn.lock` it is something only generated on the client?

In terms of the use case the first parts all worked for me but deleting the file didn't seem to make any difference–I could still navigate to it. Here is the log.

```
 INFO  compiler::run          > /Users/chrismasters/git/uwe-test-project/site/index.md -> /Users/chrismasters/git/uwe-test-project/build/debug/index.html
 INFO  uwe::build::livereload > Changed(1) in /Users/chrismasters/git/uwe-test-project/site
 INFO  workspace::project     > Delete en -> site/about.md
```

After ctrl C and rerunning it does give me an error

```
 ERROR compiler::compile  > Type error for `link`, missing url about
 ERROR uwe::opts          > panicked at 'Build failed', /home/muji/git/uwe/app/components/compiler/src/compile.rs:55:29
```

**Comment by tmpfs** [comment]
Thanks, glad it is *mostly* working!

I think i need to also delete the file from the build directory on deletion too, will raise an issue for that. Let me know what other live reload bugs you hit.

Normally lock files should be checked into a repository to pin the dependencies IMO, these issues are just due to my buggy implementation :(

**Comment by chrism** [comment]
OK great–understood.

Something I was wondering is whether you are planning to add/its possible a test suite for some of this stuff?

It seems like you have a lot to remember with making local changes and then releasing packages and maybe its a perfect use case for some quick checks to help you?

**Comment by tmpfs** [comment]
Ha ha, i have been thinking about that a lot for a long time! I have been putting it off for a while so i am not chasing my tail as things change rapidly but we are getting much closer to the point where i will start writing a test suite.

Was thinking about it again just a short while ago, you read my mind :+1:

**Comment by chrism** [comment]
Yeh, I guess its all about the right moment or where its worth doing–and I have no idea how good the testing story is with Rust though I imagine its pretty good knowing a little about Steve Klabnik's views on this stuff.

But I really think it could be nice, even if it was just to run a quick sanity check for you to make sure that there is nothing left in the code from your developments.

Again, its really easy for me to say as I'm not writing the code!

**Comment by tmpfs** [comment]
Ah yeh, we are talking at cross purposes a little, i am thinking about a test suite comprising of lots of websites using different features with assertions on the build products.

It sounds like you are talking about a sanity check that verifies their are no local plugin dependencies, is that correct? In which case this would work best as a `pre-push` git hook so i cannot push to `website` without the plugins being sane. Correct me if i misunderstand!

**Comment by chrism** [comment]
Sorry, yes there are two components to this I agree.

For the development I'd really imagine that a test suite would be really handy for you anyway–especially for the use cases you explained here

> - Open the site/index.md file and make a change to verify it reloads
> - Create a site/foo.md file and enter some text
> - Edit the site/index.md to create a link to the new page ([[foo]]) and save it (the link should be created in the web page)
> - Delete the site/foo.md file
> - Save the site/index.md file again and an error should show in the browser as the link is no longer valid

Where running this kind of thing manually tasks time and is error prone.

So yeh, I completely agree.

But I was more thinking initially of some kind of CI test run with a github action or whatever with a very bare bones series of tests just to start with which would then be filled out as you increase the test coverage.

**Comment by tmpfs** [comment]
I agree I should have both in place, I will delay the test suite until I think the compiler is more stable but not too long now then I should do that chunk of work to prevent regressions and allow easier refactoring and give us greater confidence that changes don't break existing functionality that people rely on.

I think the other point about a sanity check will be covered by `uwe task check-plugins` we are discussing elsewhere :)

**Comment by tmpfs** [comment]
Going to close this now as the integrations are working as expected, checking a project has no local dependencies is done use a `pre-push` git hook and calling `uwe task check-deps`. Also a test suite for end-to-end tests is in the works here: https://github.com/uwe-app/test.

I am going to convert the integrations documentation into a tutorial and add the commands to the new test suite.
